Repository nikandlv/jukebox, pull requests merged in 2019-07, with the labels that each got.

#6 Responsive update
  .eslintignore
  src/main/index.js
  src/renderer/App.vue
  src/renderer/components/Logo.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/store/modules/Counter.js
  src/renderer/store/modules/Sidebar.js
Labels: bug, enhancement

#10 Button component update
  src/renderer/App.vue
  src/renderer/components/Button.vue
  src/renderer/components/Logo.vue
  src/renderer/components/MenuGroup.vue
  src/renderer/layouts/DockableSidebar.vue
Labels: Component, enhancement

#11 Standardized button component and implemented focus,active,hover styles
  src/renderer/components/Button.vue
  src/renderer/layouts/DockableSidebar.vue
Labels: Bug fix, Standardize, enhancement

#12 Finished sidebar and added a better scrollbar
  package-lock.json
  package.json
  src/renderer/components/Button.vue
  src/renderer/layouts/DockableSidebar.vue
Labels: enhancement

#13 finished the action bar to an extend
  src/renderer/assets/profile.jpg
  src/renderer/components/Badge.vue
  src/renderer/components/BaseInput.vue
  src/renderer/components/History.vue
  src/renderer/components/Notification.vue
  src/renderer/components/Profile.vue
  src/renderer/layouts/ActionBar.vue
Labels: Component

#15 Added MusicBox and dependencies for color selection
  README.md
  package-lock.json
  package.json
  src/renderer/components/MusicBox.vue
  src/renderer/layouts/ActionBar.vue
  src/renderer/layouts/HomePage.vue
  static/demo/artwork-1.png
  static/demo/artwork-10.png
  static/demo/artwork-2.png
  static/demo/artwork-3.png
  static/demo/artwork-4.png
  static/demo/artwork-5.png
  static/demo/artwork-6.png
  static/demo/artwork-7.png
  static/demo/artwork-8.png
  static/demo/artwork-9.png
  static/demo/clever.jpg
  static/demo/habiba.jpg
  static/demo/starboy.png
  static/demo/test-drive.png
Labels: Component, Standardize

#17 PlayerBar update
  package-lock.json
  package.json
  src/renderer/components/MusicBox.vue
  src/renderer/layouts/PlayerBar.vue
  src/renderer/main.js
  static/demo/artwork.jpg
  static/demo/music.mp3
Labels: Component, enhancement

#18 Wavesurfer drive layer and player layout
  src/renderer/layouts/PlayerBar.vue
Labels: Component, enhancement

#19 Duration and progress update with some minor adjustments
  src/renderer/layouts/PlayerBar.vue
  src/renderer/utility/DateTime.js
Labels: enhancement

#22 Playerbar and homepage and minor changes update
  package-lock.json
  package.json
  src/renderer/components/Badge.vue
  src/renderer/components/Button.vue
  src/renderer/components/ListItem.vue
  src/renderer/components/MusicBox.vue
  src/renderer/layouts/HomePage.vue
  src/renderer/layouts/List.vue
  src/renderer/layouts/MusicRow.vue
  src/renderer/layouts/PlayerBar.vue
Labels: Component, enhancement

#24 Fixed button outlined variant text color
  src/renderer/components/Button.vue
Labels: enhancement

#25 Homepage update
  src/renderer/App.vue
  src/renderer/components/ListItem.vue
  src/renderer/layouts/HomePage.vue
Labels: Component, enhancement

#28 Development
  src/renderer/layouts/HomePage.vue
Labels: Component, enhancement

#30 Scrollbar update!
  package-lock.json
  package.json
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/layouts/HomePage.vue
Labels: enhancement

#31 General and baseline update
  src/renderer/components/ListItem.vue
  src/renderer/components/Logo.vue
  src/renderer/layouts/ArtistPage.vue
  src/renderer/layouts/ArtistsPage.vue
  src/renderer/layouts/CollectionPage.vue
  src/renderer/layouts/CollectionsPage.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/layouts/FavoritesPage.vue
  src/renderer/layouts/HomePage.vue
  src/renderer/layouts/MusicPage.vue
  src/renderer/layouts/MusicRow.vue
  src/renderer/layouts/PlaylistPage.vue
  src/renderer/router/index.js
Labels: Standardize

#38 Shorter BaseInput styling
  src/renderer/components/BaseInput.vue
Labels: Standardize

#40 Fullscreen fix, homepage bug fix and transition optimization
  src/renderer/App.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/layouts/HomePage.vue
  src/renderer/layouts/PlayerBar.vue
  src/renderer/utility/HorizontalScrollPlugin.js
Labels: Bug fix, enhancement
