Repository nikandlv/jukebox, pull requests merged in 2019-08, with the labels that each got.

#42 Dialog update
  src/renderer/components/Dialog.vue
  src/renderer/layouts/DockableSidebar.vue
Labels: enhancement

#43 Queue update
  src/renderer/layouts/ActionBar.vue
  src/renderer/layouts/PlayerBar.vue
  src/renderer/store/modules/Player.js
Labels: Feature, enhancement

#44 Updated playerbar and player state
  src/renderer/layouts/PlayerBar.vue
  src/renderer/store/modules/Player.js
Labels: Bug fix

#45 Playerbar button and queue update
  src/renderer/components/IconButton.vue
  src/renderer/layouts/PlayerBar.vue
  src/renderer/store/index.js
  src/renderer/store/modules/Player.js
Labels: Feature, enhancement

#47 Playerbar bug fix and improvement
  src/renderer/layouts/PlayerBar.vue
Labels: Bug fix

#48 Playnext logic and pause/play button update
  src/renderer/layouts/PlayerBar.vue
Labels: bug, enhancement

#49 Updated and fixed the queue logic
  src/renderer/layouts/PlayerBar.vue
  src/renderer/utility/HorizontalScrollPlugin.js
Labels: Bug fix, enhancement

#50 Dialog update
  src/renderer/components/Dialog.vue
  src/renderer/components/MenuItem.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/utility/HorizontalScrollPlugin.js
Labels: Component

#51 Dialog enhancements
  src/renderer/components/Dialog.vue
  src/renderer/layouts/DockableSidebar.vue
Labels: enhancement

#52 Bumped the current version
  package.json
Labels: good first issue

#53 Self Made Light Carosuel
  .electron-vue/webpack.main.config.js
  .electron-vue/webpack.renderer.config.js
  .electron-vue/webpack.web.config.js
  .eslintignore
  .eslintrc.js
  package-lock.json
  package.json
  src/renderer/components/Carousel.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/layouts/HomePage.vue
  src/renderer/layouts/MusicPage.vue
  src/renderer/layouts/MusicRow.vue
Labels: Component, enhancement

#54 Carousel and bug fix update
  src/renderer/components/Carousel.vue
  src/renderer/components/MenuItem.vue
  src/renderer/layouts/DockableSidebar.vue
  src/renderer/layouts/HomePage.vue
  src/renderer/layouts/MusicRow.vue
  src/renderer/layouts/PlayerBar.vue
Labels: Bug fix, enhancement
